### signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "wolf gang",
    "email": "wolfgang@gmail.com",
    "nickname": "wolf",
	"password": "123456"
    
}

### login
POST   https://pinterpets.herokuapp.com/user/login
Content-Type: application/json

{
    "email": "estoupinha@gmail.com",
	"password": "123456"
}

### Create Image
POST https://pinterpets.herokuapp.com/image/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTExOWM5LWFjNTQtNDY1My05MzhkLTQzMjI4NmE3YmE5YSIsImlhdCI6MTYxNTM5NjI2OCwiZXhwIjoxNjE1NDgyNjY4fQ.98w0i5HoAwExY4DdrxIx1o5bqEsR6OTDwwosgWqiS3w

{
    "subtitle": "wolf e sua turma",
    "date": "10/03/2021",
     "file": "https://images-na.ssl-images-amazon.com/images/I/91dU-dNxkhL.jpg",
     "tags": ["#amigoEstouAqui"],
     "collection": "Catiorro"
     }

### get All Images / get Images by Id
GET  http://localhost:3003/image/getImage
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE4Y2I2MjRmLTVmNjctNDQxNy05NTdhLTljNzM0NzYwMGZkNCIsImlhdCI6MTYxNTM5OTU0MywiZXhwIjoxNjE1NDg1OTQzfQ.aVkKAXKYyEvqVZBDGop7BKi6fKv_5quAxOkOCsjXLTg