### signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Douglas Roberto o Gato",
    "email": "douglasroberto@gmail.com",
    "nickname": "Douglas Roberto",
	"password": "123456"
    
}

### login
POST   https://pinterpets.herokuapp.com/user/login
Content-Type: application/json

{
    "email": "douglasroberto@gmail.com",
	"password": "123456"
}

### Create Image
POST http://localhost:3003/image/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxZTBiMWU0LWRkNDktNGIxNy04Zjc3LTBkOWM3YWJjNjU3OSIsImlhdCI6MTYxNTI0NTU2NSwiZXhwIjoxNjE1MjQ1ODY1fQ.JbuufXMb6wH9E4Emymlj3BfZ8DUDfpU0waim-l-8PXA

{
    "subtitle": "Business Baby",
    "date": "08/03/2021",
     "file": "https://www.instagram.com/p/BpKFAHKAMCS/?utm_source=ig_embed",
     "tags": ["#dinheiroNaCueca", "#voteEmMim"],
     "collection": "Gatos"
     }

### get All Images / get Images by Id
GET  http://localhost:3003/image/getImage
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcxZTBiMWU0LWRkNDktNGIxNy04Zjc3LTBkOWM3YWJjNjU3OSIsImlhdCI6MTYxNTIzODk3NiwiZXhwIjoxNjE1MjM5Mjc2fQ.W5CuJQcnowcRaUxVk_W-B7Vs3tV7nR1Yux4Y5FytQ_4